name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test_and_build:
    runs-on: ubuntu-latest
    env:
      BASE: /${{ github.event.repository.name }}/

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x

      - name: Cache Deno deps
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/deno
            ~/.deno
          key: ${{ runner.os }}-deno-${{ hashFiles('deno.lock', 'deno.json*') }}
          restore-keys: |
            ${{ runner.os }}-deno-

      - name: Show versions
        run: deno --version

      - name: Cache npm vite (optional)
        run: deno cache npm:vite

      - name: Run tests
        run: deno task test

      - name: Build demo
        run: deno run -A npm:vite build --config vite.config.demo.ts -- --base="${{ env.BASE }}"